config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vehicles

  authenticated :user do
    root :to => 'vehicles#index', :as => 'authenticated_root'
  end

  root :to => 'visitors_parking_pages#index'

  # visitors_parking_pages
  get 'home'    => 'visitors_parking_pages#index'
  get 'about'   => 'visitors_parking_pages#about'
  get 'contact' => 'visitors_parking_pages#contact'
  get 'help'    => 'visitors_parking_pages#help'



end

app/models/user.rb
class User < ActiveRecord::Base





  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :vehicles, dependent: :destroy

  validates :first_name, :last_name, :street_address, :city, :province, :postal, :telephone, presence: true

  PROVINCE_REGEX = /\A[A-Z]{7,30}\Z/i
  validates_format_of :province, :with => PROVINCE_REGEX, :on => :create

  POSTAL_REGEX = /\A[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]\Z/i
  validates_format_of :postal, :with => POSTAL_REGEX, :on => :create

  TELEPHONE_REGEX = /\A\(?\d{3}\)?[ .-]?\d{3}[ .-]?\d{4}\Z/
  validates_format_of :telephone, :with => TELEPHONE_REGEX, :on => :create

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  before_validation :special_chars
  before_validation :capitalize

  validates :license_plate, :manufacturer, presence: true
  validates_numericality_of :year, :only_integer => true, :allow_nil => true, :greater_than_or_equal_to => 1900, :less_than_or_equal_to => Time.new.year
  validate :maximum_vehicle_count, :on => :create

  private

  def maximum_vehicle_count
    if user.vehicles.count >= 2
      errors.add(:base, "Maximum vehicle limit reached")
    end
  end

  def special_chars
    self.license_plate = self.license_plate.gsub(/[^0-9A-Z]/i, "").upcase
  end

  def capitalize
    self.manufacturer = self.manufacturer.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :about, :contact, :help]
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:first_name, :last_name, :street_address, :city, :province, :postal, :telephone, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :street_address, :city, :province, :postal, :telephone, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :find_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if false # current_user.role.admin?
      @vehicles = Vehicle.all
      render '_admin'
    else
      @vehicles = current_user.vehicles
      render '_user'
    end
  end

  def show
  end

  def new
    @vehicle = current_user.vehicles.build
  end

  def create
    @vehicle = current_user.vehicles.build(vehicle_params)
    @vehicle.user_id = current_user.id
    if @vehicle.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @vehicle.update(vehicle_params)
      redirect_to :back
    else
      render 'edit'
    end
  end

  def destroy
    if @vehicle.destroy
      redirect_to root_path
    end
  end

  private
  def find_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  private
  def vehicle_params
    params.require(:vehicle).permit(:license_plate, :colour, :manufacturer, :model, :year, :user)
  end
end

app/controllers/visitors_parking_pages_controller.rb
class VisitorsParkingPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/visitors_parking_pages_helper.rb
module VisitorsParkingPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="navbar-static-bottom">
  <div class="container-fluid">
    <small>
      Copyright &copy; 2015 Smart Building Apps
    </small>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="main_header" class="navbar navbar-default navbar-fixed-top">
  <nav class="container">
    <%= link_to root_path, id: "logo", class: "navbar-brand" do %>
      <%= icon "car", class: "fa-1x" %> <span class="greyblue">Visitors</span>Parking
    <% end %>
    <ul class="nav navbar-nav navbar-right login-nav">
      <% if user_signed_in? %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Visitors Parking | Smart Building Apps</title>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans:700italic,400,300' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag "favicon.ico" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div id="header-img" class="container-fluid">
    <div class="row">
      <%= image_tag "parking_lot_management_software2.jpg", class: "img-responsive" %>
    </div>
  </div>

  <div id="main_content" class="container">
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/vehicles/_admin.html.erb
<%= render 'list-vehicles' %>

app/views/vehicles/_form.html.erb
<h2><%= yield(:title) %> a Vehicle</h2>
<hr>
<%= form_for @vehicle do |f| %>
  <% if @vehicle.errors.any? %>
    <ul class="error-messages">
      <% @vehicle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :license_plate %>
    <%= f.text_field :license_plate, class: "form-control",  autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :model %>
    <%= f.text_field :model, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :colour %>
    <%= f.text_field :colour, class: "form-control" %>
  </div>

  <hr>

  <div class="form-group pull-right">
    <div class="btn-group" role="group">
      <%= link_to "Back", :back, class: "btn btn-lg btn-default" %>
      <%= f.submit yield(:title), class: "btn btn-lg btn-primary pull-right btn-inline" %>
    </div>
  </div>
<% end %>

app/views/vehicles/_list_vehicles.html.erb
<div class="inline-heading">
  <h1>Registered Vehicles</h1>
  <h4 class="add-btn">
    <%= link_to  new_vehicle_path, class: "pull-right" do %>
      Add<%= icon "car", class: "grey" %>
    <% end %>
  </h4>
</div>
<hr>
<% if @vehicles.blank? %>
  <p>No Registered Vehicles</p>
<% else %>
  <table id="list-vehicles">
    <tr>
      <td>License Plate:</td>
      <td>Manufacturer:</td>
      <td>Model:</td>
      <td>Year:</td>
      <td>Colour:</td>
      <td>Paid/Unpaid</td>
      <td>Owner:</td>
    </tr>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.manufacturer %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.colour %></td>
        <td><%= vehicle.paid? %></td>
        <td><%= link_to vehicle.user.email, edit_user_registration_path %></td>
        <td><%= link_to "Edit", edit_vehicle_path(vehicle) %></td>
        <td><%= link_to "Show", vehicle_path(vehicle) %></td>
        <td><%= link_to "Delete", vehicle_path(vehicle), method: :delete, data: { confirm: "Are you sure ?"} %></td>
      </tr>
    <% end %>
  </table>
  <hr>
<% end %>

app/views/vehicles/_user.html.erb
<%= render 'list_vehicles' %>

app/views/vehicles/edit.html.erb
<% provide(:title, "Edit") %>
<div class="row">
  <div class="col-lg-offset-2 col-lg-8">
    <%= render 'form' %>
    <%= link_to "Delete", vehicle_path(@vehicle), class: "btn btn-lg btn-default", method: :delete, data: { confirm: "Are you sure ?"} %>
  </div>
</div>

app/views/vehicles/new.html.erb
<% provide(:title, "Register") %>
<div class="row">
  <div class="col-lg-offset-2 col-lg-8">
    <%= render 'form' %>
  </div>
</div>

app/views/vehicles/show.html.erb
<h2><%= current_user.first_name %>'s Vehicle</h2>
<hr>
<%= form_for @vehicle do |f| %>
  <div class="form-group">
    <%= f.label :license_plate %>
    <%= content_tag(:span, @vehicle.license_plate, class: "pull-right") %>
  </div>

  <div class="form-group">
    <%= f.label :manufacturer %>
    <%= content_tag(:span, @vehicle.manufacturer, class: "pull-right") %>
  </div>

  <div class="form-group">
    <%= f.label :model %>
    <%= content_tag(:span, @vehicle.model, class: "pull-right") %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= content_tag(:span, @vehicle.year, class: "pull-right") %>
  </div>

  <div class="form-group">
    <%= f.label :colour %>
    <%= content_tag(:span, @vehicle.colour, class: "pull-right") %>
  </div>

  <div class="form-group">
    <%= f.label :paid %>
    <%= content_tag(:span, @vehicle.paid?, class: "pull-right") %>
  </div>

  <div class="form-group">
    <%= f.label :owner %>
    <%= content_tag(:span, @vehicle.user.email, class: "pull-right") %>
  </div>

  <hr>

  <div class="form-group pull-right">
    <div class="btn-group" role="group">
      <%= link_to "Back", :back, class: "btn btn-lg btn-default" %>
      <%= link_to "Edit", edit_vehicle_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
  <%= link_to "Delete", vehicle_path(@vehicle), class: "btn btn-lg btn-default", method: :delete, data: { confirm: "Are you sure ?"} %>
<% end %>

app/views/visitors_parking_pages/about.html.erb
<h1>VisitorsParkingPages#about</h1>
<p>Find me in app/views/visitors_parking_pages/about.html.erb</p>

app/views/visitors_parking_pages/contact.html.erb
<h1>VisitorsParkingPages#contact</h1>
<p>Find me in app/views/visitors_parking_pages/contact.html.erb</p>

app/views/visitors_parking_pages/help.html.erb
<h1>VisitorsParkingPages#help</h1>
<p>Find me in app/views/visitors_parking_pages/help.html.erb</p>

app/views/visitors_parking_pages/index.html.erb
<h1>Welcome to
  <%= link_to root_path, id: "logo", class: "brand" do %>
    <%= icon "car", class: "fa-1x" %> <span class="greyblue">Visitors</span>Parking
  <% end %>
</h1>

<hr>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>